name: land_registration
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.4.1
  flutter_web3: ^2.1.9
  image_picker: ^0.8.4+3
  http: 0.13.5


  provider: ^6.0.3
  flutter_styled_toast: ^2.1.3
  hovering: ^1.0.4
  flutter_spinkit: ^5.1.0
  flutter_smart_dialog: ^4.5.4+2
  file_picker: ^5.0.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.1.3
  universal_html: ^2.0.8
  pdf: ^3.8.2
  camera: ^0.10.0+1
  camera_web: ^0.3.0
  mapbox_gl: ^0.16.0
  mapbox_search: ^3.0.1+2
  url_strategy: ^0.2.0
  fluttertoast: ^8.0.8
  animate_do: ^3.1.2
  favorite_button: ^0.0.4
  kf_drawer: ^1.1.1
  line_awesome_flutter: ^2.0.0
  supercharged: ^2.0.0
  intl: 0.18.1
  get: ^4.6.1
  flutter_staggered_grid_view: ^0.4.0
  web_socket_channel: ^2.1.0
  dart_web3: ^0.0.3
  tcard: ^1.0.0
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.9.0
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.5.3
  another_dashed_container: ^1.0.0
  google_fonts: ^4.0.4
  skeletons: ^0.0.3
  percent_indicator: ^4.2.3
  fl_chart: ^0.36.1
  ternav_icons: ^1.0.0
  introduction_screen: ^3.1.14
  fluentui_icons: ^1.0.0 # ou une version spécifique
  gap: 3.0.1 # ou une version spécifique
  barcode_widget: 2.0.2 # ou une version spécifique




dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - assets/logo.png
    - src/contracts/SmartParking.json
    - src/contracts/Land.json
    - src/contracts/Parking.json
    - images/pic/
    - images/box/
    - assets/images/
